services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "19091:19091"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:19091
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

    volumes:
      - kafka_data:/bitnami/kafka

    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'Hello' | kafka-console-producer.sh --broker-list localhost:9092 --topic test-topic > /dev/null 2>&1 && kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 15

volumes:
  kafka_data: